# Generated by Django 5.0.6 on 2024-10-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rounddetails',
            old_name='end_round',
            new_name='end_point',
        ),
        migrations.RenameField(
            model_name='rounddetails',
            old_name='start_round',
            new_name='start_point',
        ),
        migrations.RenameField(
            model_name='rounddetails',
            old_name='stops_round',
            new_name='waypoints',
        ),
    ]
