# Generated by Django 5.0.6 on 2024-10-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_end_round_rounddetails_end_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rounddetails',
            name='round_number',
        ),
    ]
