# Generated by Django 5.0.6 on 2024-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_remove_rounddetails_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounddetails',
            name='total_distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
